name: Deploy to server

on: push

jobs:
    first_jobs:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                message: ["Hola", "CodigoFacilito", "B Github Action"]
            
        steps:
            - name: Print message
              run: echo "${{ matrix.message }}"



